apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.destinationServer }}
  project: default
  source:
    path: flask-app
    repoURL: https://github.com/George-Mikulich/my-beautiful-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
