apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.destinationServer }}
  project: default
  source:
    path: samples/addons
    repoURL: https://github.com/istio/istio
    targetRevision: 1.21.3
  syncPolicy:
    automated:
      prune: true
