apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.destinationServer }}
  project: default
  source:
    repoURL: https://github.com/istio/istio
    targetRevision: 1.21.3
    path: manifests/charts/istio-control/istio-discovery
  syncPolicy:
    automated:
      prune: true
