applications:

  app-of-apps:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/George-Mikulich/my-beautiful-cluster
      targetRevision: HEAD
      path: apps
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
#
