apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask-app
  namespace: green
spec:
  hosts:
  - flask.app-georgij.com
  gateways:
  - myapp-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: flask-app.green.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
