apiVersion: dns.gcp.upbound.io/v1beta1
kind: ManagedZone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/managedzone
  name: managed-zone
spec:
  forProvider:
    description: Example DNS zone
    dnsName: app-george.com.
    visibility: private