#DOESN'T WORK


#API: https://marketplace.upbound.io/providers/upbound/provider-gcp-secretmanager/v0.41.0

apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretversion
  labels:
    composite-secret: crossplane-sa-key
  name: crossplane-sa-key
spec:
  forProvider:
    secretDataSecretRef:
      key: secret
      name: gcp-secret
      namespace: crossplane-system

---

# apiVersion: secretmanager.gcp.upbound.io/v1beta1
# kind: SecretIAMMember
# metadata:
#   annotations:
#     meta.upbound.io/example-id: secretmanager/v1beta1/secretiammember
#   name: secret-iam-member
# spec:
#   forProvider:
#     member: crossplane@my-beautiful-cluster2.iam.gserviceaccount.com
#     role: roles/viewer
#     secretId: crossplane-sa-key

---

# apiVersion: secretmanager.gcp.upbound.io/v1beta1
# kind: Secret
# metadata:
#   annotations:
#     meta.upbound.io/example-id: secretmanager/v1beta1/secretversion
#   labels:
#     composite-secret: crossplane-sa-key
#   name: secret
# spec:
#   forProvider:
#     replication:
#       - automatic: true