apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: istio-system
spec:
  secretName: app-george-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - argocd.app-george.com
  - my.app-george.com
  - kiali.app-george.com